from typing import Protocol


class SefazProvider(Protocol):
    """Future provider boundary. No network transmission is implemented in the MVP."""

    def sign(self, xml: str, certificate_reference: str) -> str: ...
    def authorize(self, signed_xml: str) -> dict: ...
    def consult(self, access_key: str) -> dict: ...
    def event(self, access_key: str, event_type: str, payload: dict) -> dict: ...
